icons_format = "{icon}"

[theme]
theme = "slick"
[theme.overrides]
idle_bg = "#000000"
# idle_fg = "#84867b"
# idle_fg="#7A5E5D"
# separator=""
# separator_fg="#FCE8c3"
good_bg="#adadad"
good_fg="#000000"

[icons]
icons = "material-nf"

# [[block]]
# block="focused_window"
# format = " $title.str(0,21) | Missing "



[[block]]
block = "disk_space"
path = "/"
info_type = "used"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 30.0
format = " $icon $used.eng(w:2) "


[[block]]
block = "sound"
headphones_indicator=true
[[block.click]]
button = "right"
cmd = "foot -e pulsemixer"

[[block]]
block="backlight"


[[block]]
block="net"
interval = 2
device="wlan0"
format=" $icon $speed_down "
format_alt=" $icon $ssid "
[[block.click]]
button = "right"
cmd = "foot -e impala"


[[block]]
block = "custom"
command = "printf ' ' && cat /home/sugan/.local/share/vpnstatus"
watch_files=["/home/sugan/.local/share/vpnstatus"]
interval="once"

[[block]]
block = "bluetooth"
adapter_mac = "3C:91:80:2D:16:BC"
mac="50:6D:81:DE:35:1C"
[block.battery_state]
"0..20" = "critical"
"21..70" = "warning"
"71..100" = "good"
[[block.click]]
button = "left"
cmd = "foot -e bluetui"

[[block]]
block = "time"
interval = 10
format = " $timestamp.datetime(f:'%b %d,%a | %I:%M %p ')"
