icons_format = "{icon}"

[theme]
theme = "srcery"
[theme.overrides]
idle_bg = "#000000"
idle_fg = "#999999"
separator="|"
separator_fg="#999999"

[icons]
icons = "material-nf"

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root:$used.eng(w:2) "


[[block]]
block = "sound"
headphones_indicator=true
[[block.click]]
button = "right"
cmd = "foot -e pulsemixer"

[[block]]
block="backlight"

[[block]]
block = "time"
interval = 10
format = "$icon  $timestamp.datetime(f:'%I:%M %p | %b %d,%a') "

[[block]]
block="net"
interval = 2
device="wlan0"
format=" $icon $speed_down "
format_alt="$icon  $ssid "
[[block.click]]
button = "right"
cmd = "foot -e impala"


[[block]]
block = "custom"
command = "printf 'vpn:' && cat /tmp/wgstate"
 watch_files=["/tmp/wgstate"]
interval="once"

[[block]]
block = "bluetooth"
adapter_mac = "3C:91:80:2D:16:BC"
mac="50:6D:81:DE:35:1C"
[block.battery_state]
"0..20" = "critical"
"21..70" = "warning"
"71..100" = "good"
[[block.click]]
button = "left"
cmd = "foot -e bluetui"

