#!/bin/bash

if bluetoothctl show | grep -q "Powered: yes"; then
	# connected_devices=$(bluetoothctl devices | awk '{print $2}' | while read mac; do
	#     if bluetoothctl info "$mac" | grep -q "Connected: yes"; then
	# 	bluetoothctl info "$mac" | grep "Name" | head -n1 | cut -d ' ' -f 2-
	#     fi
	# done)
    echo " |  ON"
else
    echo " |  OFF"
fi




