#!/bin/sh

# Default text
output="| 󰤢 : $(cat /sys/class/net/wlan0/operstate)"

# If left-clicked, add SSID
case $BLOCK_BUTTON in
    1) ssid="$(iwgetid -r)"
       output="$output | $ssid"
       ;;
esac

echo "$output"

